baseURL = 'https://moloxiao.github.io/'
languageCode = 'en-us'
title = "Shan's blog"
author = "Shan"
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 10
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 2

[params.homeInfoParams]
    Title = "Welcome to Shan's Blog"
    Content = "Welcome to my blog. I'm Shan Xiao, a handmade programmer. Here, I write about technology, programming, open source, and anything else that comes to mind. Let's learn and grow together. If you're interested, here are some of my side projects : [SSM](https://ssm.micostupid.com), [Kids Story](https://kids-story-omega.vercel.app), [Resume Manager](https://resumemanager.pages.dev/), [Nathaniel Pomodoro](https://nathaniel-pomodoro.vercel.app/)"
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/moloxiao"
    [[params.socialIcons]]
        name = "twitter"
        url = "https://x.com/shanxiao_sx"

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"